//! Store code generation — 11 store kinds → Rust struct stubs with connector annotations.

use crate::ast::*;
use super::RustEmitter;

impl RustEmitter {
    /// Emit Rust struct stubs for a store declaration.
    ///
    /// For each store kind, emits doc-commented struct definitions with the
    /// intended connector noted. Full connector integration is out of scope —
    /// this provides the typed surface that a connector crate would implement.
    pub fn codegen_store(&self, store: &StoreDef) -> String {
        let mut out = String::new();
        match &store.kind {
            StoreKind::Relational => self.codegen_relational_store(store, &mut out),
            StoreKind::KeyValue   => self.codegen_keyvalue_store(store, &mut out),
            StoreKind::Document   => self.codegen_document_store(store, &mut out),
            StoreKind::Columnar   => self.codegen_columnar_store(store, &mut out),
            StoreKind::Snowflake  => self.codegen_snowflake_store(store, &mut out),
            StoreKind::Hypercube  => self.codegen_hypercube_store(store, &mut out),
            _ => {
                out.push_str(&format!(
                    "// Generated by Loom — store: {} :: {:?}\n",
                    store.name, store.kind
                ));
            }
        }
        out
    }

    fn codegen_relational_store(&self, store: &StoreDef, out: &mut String) {
        out.push_str(&format!(
            "// Generated by Loom — M93 Relational store: {}\n",
            store.name
        ));
        out.push_str("// Connector: SQL (PostgreSQL/SQLite via sqlx)\n");
        for entry in &store.schema {
            if let StoreSchemaEntry::Table { name, fields, .. } = entry {
                let pk_field = fields.iter()
                    .find(|f| f.annotations.iter().any(|a| a.key == "primary_key"))
                    .map(|f| f.name.as_str())
                    .unwrap_or("(none)");
                out.push_str(&format!(
                    "// Table: {} — primary key: {}\n",
                    name, pk_field
                ));
                out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                out.push_str(&format!("pub struct {} {{\n", name));
                for field in fields {
                    out.push_str(&format!(
                        "    pub {}: {},\n",
                        field.name,
                        self.emit_type_expr(&field.ty)
                    ));
                }
                out.push_str("}\n");
            }
        }
    }

    fn codegen_keyvalue_store(&self, store: &StoreDef, out: &mut String) {
        out.push_str(&format!(
            "// Generated by Loom — M93 KeyValue store: {}\n",
            store.name
        ));
        out.push_str("// Connector: Redis / in-process DashMap\n");

        let key_type = store.schema.iter().find_map(|e| {
            if let StoreSchemaEntry::KeyType { ty, .. } = e {
                Some(self.emit_type_expr(ty))
            } else {
                None
            }
        }).unwrap_or_else(|| "()".to_string());

        let value_type = store.schema.iter().find_map(|e| {
            if let StoreSchemaEntry::ValueType { ty, .. } = e {
                Some(self.emit_type_expr(ty))
            } else {
                None
            }
        }).unwrap_or_else(|| "()".to_string());

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str(&format!("pub struct {}Entry {{\n", store.name));
        out.push_str(&format!("    pub key: {},\n", key_type));
        out.push_str(&format!("    pub value: {},\n", value_type));
        out.push_str("}\n");
    }

    fn codegen_document_store(&self, store: &StoreDef, out: &mut String) {
        out.push_str(&format!(
            "// Generated by Loom — M93 Document store: {}\n",
            store.name
        ));
        out.push_str("// Connector: MongoDB / sled / DocumentDB\n");
        for entry in &store.schema {
            if let StoreSchemaEntry::Collection { name, fields, .. } = entry {
                out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                out.push_str(&format!("pub struct {} {{\n", name));
                for field in fields {
                    let rust_ty = match &field.ty {
                        TypeExpr::Base(n) if n == "Json" => "serde_json::Value".to_string(),
                        other => self.emit_type_expr(other),
                    };
                    out.push_str(&format!("    pub {}: {},\n", field.name, rust_ty));
                }
                out.push_str("}\n");
            }
        }
    }

    fn codegen_columnar_store(&self, store: &StoreDef, out: &mut String) {
        out.push_str(&format!(
            "// Generated by Loom — M94 Columnar store: {}\n",
            store.name
        ));
        out.push_str("// Connector: Apache Arrow / Parquet / DuckDB\n");
        for entry in &store.schema {
            if let StoreSchemaEntry::Collection { name, fields, .. } = entry {
                out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                out.push_str(&format!("pub struct {} {{\n", name));
                for field in fields {
                    out.push_str(&format!(
                        "    pub {}: {},\n",
                        field.name,
                        self.emit_type_expr(&field.ty)
                    ));
                }
                out.push_str("}\n");
            }
        }
    }

    fn codegen_snowflake_store(&self, store: &StoreDef, out: &mut String) {
        out.push_str(&format!(
            "// Generated by Loom — M94 Snowflake store: {}\n",
            store.name
        ));
        out.push_str("// Connector: Snowflake / BigQuery / Redshift\n");
        for entry in &store.schema {
            match entry {
                StoreSchemaEntry::Fact { name, fields, .. } => {
                    out.push_str(&format!("// Fact table: {}\n", name));
                    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                    out.push_str(&format!("pub struct {} {{\n", name));
                    for field in fields {
                        out.push_str(&format!(
                            "    pub {}: {},\n",
                            field.name,
                            self.emit_type_expr(&field.ty)
                        ));
                    }
                    out.push_str("}\n");
                }
                StoreSchemaEntry::DimensionEntry { name, fields, .. } => {
                    out.push_str(&format!("// Dimension table: {}\n", name));
                    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                    out.push_str(&format!("pub struct {} {{\n", name));
                    for field in fields {
                        out.push_str(&format!(
                            "    pub {}: {},\n",
                            field.name,
                            self.emit_type_expr(&field.ty)
                        ));
                    }
                    out.push_str("}\n");
                }
                _ => {}
            }
        }
    }

    fn codegen_hypercube_store(&self, store: &StoreDef, out: &mut String) {
        out.push_str(&format!(
            "// Generated by Loom — M94 Hypercube store: {}\n",
            store.name
        ));
        out.push_str("// Connector: MOLAP / in-process ndarray\n");
        for entry in &store.schema {
            match entry {
                StoreSchemaEntry::DimensionEntry { name, fields, .. } => {
                    out.push_str(&format!("// Dimension (axis): {}\n", name));
                    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                    out.push_str(&format!("pub struct {} {{\n", name));
                    for field in fields {
                        out.push_str(&format!(
                            "    pub {}: {},\n",
                            field.name,
                            self.emit_type_expr(&field.ty)
                        ));
                    }
                    out.push_str("}\n");
                }
                StoreSchemaEntry::Fact { name, fields, .. } => {
                    out.push_str(&format!("// Fact (measure): {}\n", name));
                    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
                    out.push_str(&format!("pub struct {} {{\n", name));
                    for field in fields {
                        out.push_str(&format!(
                            "    pub {}: {},\n",
                            field.name,
                            self.emit_type_expr(&field.ty)
                        ));
                    }
                    out.push_str("}\n");
                }
                _ => {}
            }
        }
    }
}
