//! Orchestration loop — the BIOISO evolution daemon (R7).
//!
//! The orchestrator closes the full feedback loop:
//!
//! ```text
//! collect signals → evaluate telos drift → propose (T1)
//!     → escalate (T2 if needed) → escalate (T3 if needed)
//!     → type-safe gate → canary deploy → monitor → promote/rollback
//! ```
//!
//! # Usage
//!
//! ```rust,ignore
//! let rt = Runtime::new("bioiso.db").unwrap();
//! let mut orch = Orchestrator::new(rt, OrchestratorConfig::default());
//! orch.run_once().unwrap(); // single tick (useful for tests / CLI)
//! ```
//!
//! The daemon loop (`run_loop`) can be run in a background thread.  It will
//! execute `run_once` on the configured `tick_interval`.

use std::time::Duration;

use crate::runtime::{
    circadian::CircadianVerdict,
    deploy::{CanaryDeployer, DeployOutcome, DeployStatus},
    drift::DriftEvent,
    gate::GateVerdict,
    mutation::MutationProposal,
    store::SignalStore,
    Runtime,
};

// ── Config ────────────────────────────────────────────────────────────────────

/// Orchestration loop configuration.
#[derive(Debug, Clone)]
pub struct OrchestratorConfig {
    /// How many recent signals to include when evaluating drift.
    pub drift_lookback: usize,
    /// Number of consecutive Tier 1 misses before escalating to Tier 2.
    pub tier1_fail_threshold: u32,
    /// Number of consecutive Tier 2 misses before escalating to Tier 3.
    pub tier2_fail_threshold: u32,
    /// Sleep between ticks when run in daemon mode.
    pub tick_interval: Duration,
    /// Fraction of entities to include in canary (0.0–1.0). Default 0.1 (10%).
    pub canary_fraction: f64,
    /// How many ticks to monitor after a canary deploy before promoting.
    pub canary_monitor_ticks: u32,
    /// How many ticks between epigenome distillation passes.
    pub epigenome_distil_interval: u32,
}

impl Default for OrchestratorConfig {
    fn default() -> Self {
        Self {
            drift_lookback: 20,
            tier1_fail_threshold: 3,
            tier2_fail_threshold: 3,
            tick_interval: Duration::from_secs(5),
            canary_fraction: 0.1,
            canary_monitor_ticks: 3,
            epigenome_distil_interval: 10,
        }
    }
}

// ── TickResult ────────────────────────────────────────────────────────────────

/// Result of a single orchestrator tick.
#[derive(Debug)]
pub struct TickResult {
    /// Drift events detected in this tick.
    pub drift_events: Vec<DriftEvent>,
    /// Proposals generated by whichever tier fired.
    pub proposals: Vec<MutationProposal>,
    /// Which tier produced the proposals (1, 2, or 3).  `None` if no drift.
    pub tier_used: Option<u8>,
    /// Outcomes of canary deployments for each accepted proposal.
    pub deploy_outcomes: Vec<DeployOutcome>,
    /// How many drift events were suppressed by the Circadian gate this tick.
    pub circadian_suppressed: usize,
    /// Whether the epigenome distillation pass ran this tick.
    pub distillation_ran: bool,
}

// ── Orchestrator ──────────────────────────────────────────────────────────────

/// The BIOISO evolution orchestrator.
pub struct Orchestrator {
    /// The full runtime context (store + supervisor + all synthesis tiers).
    pub runtime: Runtime,
    /// Orchestration configuration.
    pub config: OrchestratorConfig,
    /// Per-entity Tier 1 failure counters (entity_id → consecutive miss count).
    pub tier1_fail_counts: std::collections::HashMap<String, u32>,
    /// Per-entity Tier 2 failure counters.
    pub tier2_fail_counts: std::collections::HashMap<String, u32>,
    /// The canary deployer.
    deployer: CanaryDeployer,
    /// Monotonically increasing tick counter — drives periodic tasks.
    tick_count: u64,
}

impl Orchestrator {
    /// Create a new orchestrator wrapping the given runtime.
    pub fn new(runtime: Runtime, config: OrchestratorConfig) -> Self {
        Self {
            runtime,
            config,
            tier1_fail_counts: std::collections::HashMap::new(),
            tier2_fail_counts: std::collections::HashMap::new(),
            deployer: CanaryDeployer::new(),
            tick_count: 0,
        }
    }

    /// Run one full evolution tick.
    ///
    /// CEMS wiring per tick:
    /// - **M axis**: `mycelium.tick()` — pheromone evaporation + metabolic load EMA.
    /// - **C axis**: Circadian gate checked per entity before mutation proposals.
    /// - **E axis**: Epigenome distillation every `epigenome_distil_interval` ticks.
    /// - **Sampler**: `record_outcome()` fed from canary deploy results.
    ///
    /// Returns a [`TickResult`] summarising what happened.
    pub fn run_once(&mut self) -> Result<TickResult, rusqlite::Error> {
        self.tick_count += 1;

        // ── M axis: mycelium tick (pheromone evaporation + metabolic EMA) ──────
        self.runtime.mycelium.tick(1);

        // ── E axis: periodic epigenome distillation ────────────────────────────
        let distillation_ran =
            self.tick_count % self.config.epigenome_distil_interval as u64 == 0;
        if distillation_ran {
            let now_ts = crate::runtime::signal::now_ms();
            self.runtime.epigenome.distil_working_to_core(3, "orchestrator", now_ts);
            self.runtime.epigenome.distil_high_drift_to_core(0.7, "orchestrator", now_ts);
        }

        // ── Evaluate drift ─────────────────────────────────────────────────────
        let drift_events =
            self.runtime.evaluate_all_drift(self.config.drift_lookback)?;

        if drift_events.is_empty() {
            return Ok(TickResult {
                drift_events: vec![],
                proposals: vec![],
                tier_used: None,
                deploy_outcomes: vec![],
                circadian_suppressed: 0,
                distillation_ran,
            });
        }

        // ── C axis: circadian gate — filter suppressed entities ────────────────
        let ts_ms = crate::runtime::signal::now_ms();
        let now = crate::runtime::circadian::WallTime::from_unix_ms(ts_ms);
        let mut suppressed = 0usize;
        let mut active_events: Vec<&DriftEvent> = Vec::new();

        for event in &drift_events {
            let verdict = self.runtime.circadian.evaluate(&event.entity_id, &now);
            match verdict {
                CircadianVerdict::Suppress | CircadianVerdict::DeferMutations => {
                    suppressed += 1;
                }
                CircadianVerdict::Allow => {
                    active_events.push(event);
                }
            }
        }

        // ── Tier cascade ───────────────────────────────────────────────────────
        let mut all_proposals: Vec<MutationProposal> = Vec::new();
        let mut tier_used: Option<u8> = None;

        for event in &active_events {
            let (proposals, tier) = self.propose_for_event(event);
            if !proposals.is_empty() {
                tier_used = Some(tier);
                all_proposals.extend(proposals);
                break;
            }
        }

        // ── Gate ───────────────────────────────────────────────────────────────
        let mut accepted: Vec<MutationProposal> = Vec::new();
        for proposal in all_proposals {
            let result = self.runtime.apply_proposal(&proposal);
            if matches!(result.verdict, GateVerdict::Accepted) {
                accepted.push(proposal);
            } else {
                // Gate rejection is negative feedback — the mutation was structurally invalid.
                self.runtime.sampler.record_outcome(false);
            }
        }

        // ── Canary deploy + sampler feedback ──────────────────────────────────
        let mut deploy_outcomes = Vec::new();
        for proposal in &accepted {
            let outcome = self.deployer.deploy(proposal, &self.runtime.store);
            // Feed the deploy result back into the sampler for adaptive σ.
            let promoted = outcome.status == DeployStatus::Promoted;
            self.runtime.sampler.record_outcome(promoted);
            deploy_outcomes.push(outcome);
        }

        Ok(TickResult {
            drift_events,
            proposals: accepted,
            tier_used,
            deploy_outcomes,
            circadian_suppressed: suppressed,
            distillation_ran,
        })
    }

    /// Run the daemon loop. Blocks the calling thread. Returns on `stop_requested`.
    ///
    /// Use `std::thread::spawn` to run in the background.
    pub fn run_loop(&mut self, stop_requested: &std::sync::atomic::AtomicBool) {
        while !stop_requested.load(std::sync::atomic::Ordering::Relaxed) {
            let _ = self.run_once();
            std::thread::sleep(self.config.tick_interval);
        }
    }

    // ── Tier cascade ─────────────────────────────────────────────────────────

    fn propose_for_event(&mut self, event: &DriftEvent) -> (Vec<MutationProposal>, u8) {
        let eid = &event.entity_id;

        // Tier 1 — deterministic rule engine.
        let t1_proposals = self.runtime.propose_mutations(event, None);
        if !t1_proposals.is_empty() {
            self.tier1_fail_counts.insert(eid.clone(), 0);
            return (t1_proposals, 1);
        }

        let t1_fails = self.tier1_fail_counts.entry(eid.clone()).or_insert(0);
        *t1_fails += 1;

        if *t1_fails < self.config.tier1_fail_threshold {
            return (vec![], 1);
        }

        // Tier 2 — Ganglion (Ollama).
        let t2_proposals = self.runtime.ganglion.evaluate(event, &self.runtime.store);
        if !t2_proposals.is_empty() {
            self.tier2_fail_counts.insert(eid.clone(), 0);
            return (t2_proposals, 2);
        }

        let t2_fails = self.tier2_fail_counts.entry(eid.clone()).or_insert(0);
        *t2_fails += 1;

        if *t2_fails < self.config.tier2_fail_threshold {
            return (vec![], 2);
        }

        // Tier 3 — Mammal Brain (Claude).
        let t3_proposals = self.runtime.evaluate_tier3(event, None);
        if !t3_proposals.is_empty() {
            self.tier2_fail_counts.insert(eid.clone(), 0);
            return (t3_proposals, 3);
        }

        (vec![], 3)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::polycephalum::{RuleCondition, RuleRegistry, RuleAction, DeltaSpec, Rule};

    fn default_orchestrator() -> Orchestrator {
        let rt = Runtime::new(":memory:").unwrap();
        Orchestrator::new(rt, OrchestratorConfig::default())
    }

    #[test]
    fn tick_with_no_entities_returns_empty_result() {
        let mut orch = default_orchestrator();
        let result = orch.run_once().unwrap();
        assert!(result.drift_events.is_empty());
        assert!(result.proposals.is_empty());
        assert!(result.tier_used.is_none());
    }

    #[test]
    fn tick_with_no_drift_returns_empty_result() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("e1", "Test", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("e1", "temperature", Some(0.0), Some(100.0), Some(50.0))
            .unwrap();
        // Emit a signal well within bounds.
        orch.runtime.emit_metric("e1", "temperature", 50.0).unwrap();
        let result = orch.run_once().unwrap();
        assert!(result.drift_events.is_empty());
    }

    #[test]
    fn tick_with_drift_invokes_tier1_when_rule_matches() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("forest", "ForestModel", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("forest", "carbon_stock", Some(0.0), Some(100.0), Some(80.0))
            .unwrap();

        // Register a Tier 1 rule.
        let rule = Rule {
            name: "boost_carbon".into(),
            priority: 10,
            condition: RuleCondition { metric: "carbon_stock".into(), min_score: 0.3, max_score: 1.01, min_severity: crate::runtime::DriftSeverity::Healthy },
            action: RuleAction::AdjustParam {
                param: "carbon_input".into(),
                delta: DeltaSpec::Fixed(5.0),
            },
        };
        let mut registry = RuleRegistry::new();
        registry.add_for_entity("forest", rule);
        orch.runtime.polycephalum = crate::runtime::Polycephalum::with_registry(registry);

        // Emit a drifted signal.
        orch.runtime.emit_metric("forest", "carbon_stock", 5.0).unwrap();

        let result = orch.run_once().unwrap();
        // Drift should have been detected.
        assert!(!result.drift_events.is_empty());
        // Tier 1 should have fired (even if gate rejects — tier_used reflects the tier that
        // produced proposals, not whether they passed the gate).
        assert_eq!(result.tier_used, Some(1));
    }

    #[test]
    fn tier1_fail_counter_increments_on_miss() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("ent", "E", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("ent", "m", Some(0.0), Some(1.0), Some(0.9))
            .unwrap();
        // Emit a badly drifted value — no Tier 1 rules registered, so T1 will miss.
        orch.runtime.emit_metric("ent", "m", 0.0).unwrap();
        let _ = orch.run_once();
        let count = *orch.tier1_fail_counts.get("ent").unwrap_or(&0);
        assert_eq!(count, 1);
    }

    #[test]
    fn mycelium_tick_called_each_run_once() {
        // Mycelium tick increments; we verify that after N run_once calls the
        // metabolic EMA has been updated (non-zero ticks seen).
        let mut orch = default_orchestrator();
        for _ in 0..5 {
            orch.run_once().unwrap();
        }
        // After 5 ticks with 0 signals, metabolic load should be 0 (EMA of 0),
        // but the tick count on the orchestrator must be 5.
        assert_eq!(orch.tick_count, 5);
    }

    #[test]
    fn distillation_runs_on_configured_interval() {
        let mut cfg = OrchestratorConfig::default();
        cfg.epigenome_distil_interval = 3;
        let rt = Runtime::new(":memory:").unwrap();
        let mut orch = Orchestrator::new(rt, cfg);

        let r1 = orch.run_once().unwrap(); // tick 1
        let r2 = orch.run_once().unwrap(); // tick 2
        let r3 = orch.run_once().unwrap(); // tick 3 — distil fires
        assert!(!r1.distillation_ran);
        assert!(!r2.distillation_ran);
        assert!(r3.distillation_ran);
    }

    #[test]
    fn circadian_suppress_reduces_active_events() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("gated", "Gated", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("gated", "x", Some(0.0), Some(1.0), Some(0.9))
            .unwrap();

        // Add a Suppress schedule matching every minute (wildcard = always matches).
        orch.runtime
            .circadian
            .add_gate(
                "always_suppress",
                "* * * * *",
                crate::runtime::CircadianAction::Suppress,
                Some("gated".into()),
            )
            .expect("invalid cron expression");

        // Emit a drifted signal.
        orch.runtime.emit_metric("gated", "x", 0.0).unwrap();

        let result = orch.run_once().unwrap();
        // Drift is detected, but the circadian gate suppresses mutations.
        assert_eq!(result.circadian_suppressed, 1, "expected 1 suppressed event");
        assert!(result.proposals.is_empty(), "no proposals when suppressed");
    }

    #[test]
    fn sampler_acceptance_updated_after_promoted_deploy() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("e1", "E1", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("e1", "v", Some(0.0), Some(100.0), Some(50.0))
            .unwrap();

        // Register a rule so Tier 1 proposes something.
        let rule = Rule {
            name: "boost_v".into(),
            priority: 10,
            condition: RuleCondition {
                metric: "v".into(),
                min_score: 0.3,
                max_score: 1.01,
                min_severity: crate::runtime::DriftSeverity::Healthy,
            },
            action: RuleAction::AdjustParam {
                param: "v_input".into(),
                delta: DeltaSpec::Fixed(5.0),
            },
        };
        let mut registry = RuleRegistry::new();
        registry.add_for_entity("e1", rule);
        orch.runtime.polycephalum = crate::runtime::Polycephalum::with_registry(registry);

        // Emit a badly-drifted signal — gate will reject the proposal but
        // that counts as negative feedback to the sampler.
        orch.runtime.emit_metric("e1", "v", 2.0).unwrap();
        orch.run_once().unwrap();

        // Sampler should have recorded at least one outcome.
        assert!(!orch.runtime.sampler.acceptance.is_empty());
    }
}
