//! Orchestration loop — the BIOISO evolution daemon (R7).
//!
//! The orchestrator closes the full feedback loop:
//!
//! ```text
//! collect signals → evaluate telos drift → propose (T1)
//!     → escalate (T2 if needed) → escalate (T3 if needed)
//!     → type-safe gate → canary deploy → monitor → promote/rollback
//! ```
//!
//! # Usage
//!
//! ```rust,ignore
//! let rt = Runtime::new("bioiso.db").unwrap();
//! let mut orch = Orchestrator::new(rt, OrchestratorConfig::default());
//! orch.run_once().unwrap(); // single tick (useful for tests / CLI)
//! ```
//!
//! The daemon loop (`run_loop`) can be run in a background thread.  It will
//! execute `run_once` on the configured `tick_interval`.

use std::collections::HashMap;
use std::time::Duration;

use crate::runtime::{
    circadian::CircadianVerdict,
    colony::GossipMessage,
    deploy::{CanaryDeployer, DeployOutcome, DeployStatus},
    drift::DriftEvent,
    epigenetic::MemoryType,
    gate::GateVerdict,
    mutation::MutationProposal,
    solver_tiers::{self, MetricObservation, N_HEURISTICS},
    supervisor::EntityState,
    Runtime,
};

// ── Config ────────────────────────────────────────────────────────────────────

/// Orchestration loop configuration.
#[derive(Debug, Clone)]
pub struct OrchestratorConfig {
    /// How many recent signals to include when evaluating drift.
    pub drift_lookback: usize,
    /// Number of consecutive Tier 1 misses before escalating to Tier 2.
    pub tier1_fail_threshold: u32,
    /// Number of consecutive Tier 2 misses before escalating to Tier 3.
    pub tier2_fail_threshold: u32,
    /// Sleep between ticks when run in daemon mode.
    pub tick_interval: Duration,
    /// Fraction of entities to include in canary (0.0–1.0). Default 0.1 (10%).
    pub canary_fraction: f64,
    /// How many ticks to monitor after a canary deploy before promoting.
    pub canary_monitor_ticks: u32,
    /// How many ticks between epigenome distillation passes.
    pub epigenome_distil_interval: u32,
    /// Minimum ticks between Tier 2 (Ganglion/Claude) calls **per entity**.
    ///
    /// When T1 consistently produces zero proposals every entity escalates to T2
    /// after `tier1_fail_threshold` ticks, which means T2 fires continuously and
    /// burns API budget.  This cooldown prevents T2 from firing more often than
    /// once every N ticks per entity regardless of T1 miss counts.
    ///
    /// Configured via the `T2_MIN_INTERVAL_TICKS` environment variable.
    /// Default: 100 (≈ 8 min at a 5 s tick, ~97 % cost reduction vs no guard).
    pub t2_min_interval_ticks: u64,

    /// D_static threshold above which T3 (Brain/Sonnet) is additionally invoked
    /// even when T2 produced proposals.
    ///
    /// For BIOISO domains, Haiku (T2) almost always returns `parameter_adjust`.
    /// When drift is persistently above this threshold — meaning ParameterAdjust
    /// is not converging — T3 is called to evaluate whether `structural_rewire`
    /// is warranted.  Set to `f64::MAX` to disable.
    ///
    /// Configured via `STRUCTURAL_REWIRE_THRESHOLD`. Default: 0.35.
    pub structural_rewire_threshold: f64,
}

impl Default for OrchestratorConfig {
    fn default() -> Self {
        let t2_min = std::env::var("T2_MIN_INTERVAL_TICKS")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(100u64);
        let rewire_thresh = std::env::var("STRUCTURAL_REWIRE_THRESHOLD")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(0.35f64);
        Self {
            drift_lookback: 20,
            tier1_fail_threshold: 3,
            tier2_fail_threshold: 3,
            tick_interval: Duration::from_secs(5),
            canary_fraction: 0.1,
            canary_monitor_ticks: 3,
            epigenome_distil_interval: 10,
            t2_min_interval_ticks: t2_min,
            structural_rewire_threshold: rewire_thresh,
        }
    }
}

// ── TickResult ────────────────────────────────────────────────────────────────

/// Result of a single orchestrator tick.
#[derive(Debug)]
pub struct TickResult {
    /// Drift events detected in this tick.
    pub drift_events: Vec<DriftEvent>,
    /// Proposals generated by whichever tier fired.
    pub proposals: Vec<MutationProposal>,
    /// Which tier produced the proposals (1, 2, or 3).  `None` if no drift.
    pub tier_used: Option<u8>,
    /// Outcomes of canary deployments for each accepted proposal.
    pub deploy_outcomes: Vec<DeployOutcome>,
    /// How many drift events were suppressed by the Circadian gate this tick.
    pub circadian_suppressed: usize,
    /// Whether the epigenome distillation pass ran this tick.
    pub distillation_ran: bool,
    /// Number of inbound gossip messages absorbed into the epigenome.
    pub gossip_absorbed: usize,
    /// Number of security events absorbed into the epigenome security tier.
    pub security_absorbed: usize,
}

// ── Orchestrator ──────────────────────────────────────────────────────────────

/// The BIOISO evolution orchestrator.
pub struct Orchestrator {
    /// The full runtime context (store + supervisor + all synthesis tiers).
    pub runtime: Runtime,
    /// Orchestration configuration.
    pub config: OrchestratorConfig,
    /// Per-entity Tier 1 failure counters (entity_id → consecutive miss count).
    pub tier1_fail_counts: HashMap<String, u32>,
    /// Per-entity Tier 2 failure counters.
    pub tier2_fail_counts: HashMap<String, u32>,
    /// Tick at which T2 last fired per entity — enforces `t2_min_interval_ticks`.
    pub last_t2_tick: HashMap<String, u64>,
    /// The canary deployer.
    deployer: CanaryDeployer,
    /// Monotonically increasing tick counter — drives periodic tasks.
    tick_count: u64,
    /// Saturation tracking: last (param, delta_positive) promoted per entity.
    saturation_track: HashMap<String, (String, bool, u32)>,

    // ── Solver-tier state (T1–T4 internal proposal generators) ───────────────
    /// SA temperature per entity (T2 solver tier). Starts at 5.0, decays each tick.
    pub t2_temperature: HashMap<String, f64>,
    /// SARSA weight table per entity (T3 solver tier). Normalised over N_HEURISTICS.
    pub t3_weights: HashMap<String, [f64; N_HEURISTICS]>,
    /// GP-UCB metric observation history per entity (T4 solver tier).
    pub t4_history: HashMap<String, HashMap<String, MetricObservation>>,
    /// Total GP-UCB observations made per entity (T4).
    pub t4_total_obs: HashMap<String, u32>,
    /// LCG RNG state for T2/T3 stochastic generators (seeded from tick_count).
    rng_state: u64,
}

impl Orchestrator {
    /// Create a new orchestrator wrapping the given runtime.
    pub fn new(runtime: Runtime, config: OrchestratorConfig) -> Self {
        Self {
            runtime,
            config,
            tier1_fail_counts: HashMap::new(),
            tier2_fail_counts: HashMap::new(),
            last_t2_tick: HashMap::new(),
            deployer: CanaryDeployer::new(),
            tick_count: 0,
            saturation_track: HashMap::new(),
            t2_temperature: HashMap::new(),
            t3_weights: HashMap::new(),
            t4_history: HashMap::new(),
            t4_total_obs: HashMap::new(),
            rng_state: 0xcafe_babe_dead_beef,
        }
    }

    /// Run one full evolution tick.
    ///
    /// CEMS wiring per tick:
    /// - **M axis**: `mycelium.tick()` — pheromone evaporation + metabolic load EMA.
    /// - **M gossip**: drain inbound gossip → absorb into epigenome as Relational memories.
    /// - **C axis**: Circadian gate checked per entity before mutation proposals.
    /// - **E axis**: Epigenome distillation every `epigenome_distil_interval` ticks.
    /// - **E security**: Absorb membrane security events into epigenome Core.
    /// - **Sampler**: `record_outcome()` fed from canary deploy results.
    /// - **Pheromone**: deposit on strategy trail for every promoted mutation.
    ///
    /// Returns a [`TickResult`] summarising what happened.
    pub fn run_once(&mut self) -> Result<TickResult, rusqlite::Error> {
        self.tick_count += 1;
        let now_ts = crate::runtime::signal::now_ms();

        // ── M axis: mycelium tick (pheromone evaporation + metabolic EMA) ──────
        self.runtime.mycelium.tick(now_ts);

        // ── M gossip: absorb inbound Core snapshots from peers ─────────────────
        let inbound: Vec<GossipMessage> = self.runtime.mycelium.drain_inbound();
        let gossip_absorbed = inbound.len();
        for msg in inbound {
            // Write peer's Core snapshot as Relational memory (cross-entity knowledge).
            self.runtime.epigenome.write_core(
                &msg.sender_id,
                format!("[gossip@{}] {}", msg.ts, msg.core_snapshot),
                MemoryType::Relational,
                "mycelium",
                now_ts,
            );
        }

        // ── E axis: periodic epigenome distillation ────────────────────────────
        let distillation_ran = self.tick_count % self.config.epigenome_distil_interval as u64 == 0;
        if distillation_ran {
            self.runtime
                .epigenome
                .distil_working_to_core(3, "orchestrator", now_ts);
            self.runtime
                .epigenome
                .distil_high_drift_to_core(0.7, "orchestrator", now_ts);
        }

        // ── Evaluate drift ─────────────────────────────────────────────────────
        let drift_events = self
            .runtime
            .evaluate_all_drift(self.config.drift_lookback)?;

        // ── E security: absorb membrane events for all active entities ─────────
        let entity_ids: Vec<String> = self
            .runtime
            .supervisor
            .living_entity_ids()
            .into_iter()
            .collect();
        let mut security_absorbed = 0usize;
        for eid in &entity_ids {
            let before = self.runtime.epigenome.core_entries(eid).len();
            self.runtime
                .epigenome
                .absorb_security_events(eid, &self.runtime.store, 50, now_ts);
            security_absorbed += self
                .runtime
                .epigenome
                .core_entries(eid)
                .len()
                .saturating_sub(before);
        }

        if drift_events.is_empty() {
            return Ok(TickResult {
                drift_events: vec![],
                proposals: vec![],
                tier_used: None,
                deploy_outcomes: vec![],
                circadian_suppressed: 0,
                distillation_ran,
                gossip_absorbed,
                security_absorbed,
            });
        }

        // ── C axis: circadian gate — filter suppressed entities ────────────────
        let now = crate::runtime::circadian::WallTime::from_unix_ms(now_ts);
        let mut suppressed = 0usize;
        let mut active_events: Vec<&DriftEvent> = Vec::new();

        for event in &drift_events {
            let verdict = self.runtime.circadian.evaluate(&event.entity_id, &now);
            match verdict {
                CircadianVerdict::Suppress | CircadianVerdict::DeferMutations => {
                    suppressed += 1;
                }
                CircadianVerdict::Allow => {
                    active_events.push(event);
                }
            }
        }

        // ── Tier cascade ───────────────────────────────────────────────────────
        let mut all_proposals: Vec<MutationProposal> = Vec::new();
        let mut tier_used: Option<u8> = None;

        for event in &active_events {
            let (proposals, tier) = self.propose_for_event(event);
            if !proposals.is_empty() {
                tier_used = Some(tier);
                all_proposals.extend(proposals);
                break;
            }
        }

        // ── Gate ───────────────────────────────────────────────────────────────
        let mut accepted: Vec<MutationProposal> = Vec::new();
        for proposal in all_proposals {
            let result = self.runtime.apply_proposal(&proposal);
            if matches!(result.verdict, GateVerdict::Accepted) {
                accepted.push(proposal);
            } else {
                // Gate rejection is negative feedback — the mutation was structurally invalid.
                self.runtime.sampler.record_outcome(false);
            }
        }

        // ── Canary deploy + sampler feedback + pheromone deposit ──────────────
        let mut deploy_outcomes = Vec::new();
        for proposal in &accepted {
            let outcome = self.deployer.deploy(proposal, &self.runtime.store);
            let promoted = outcome.status == DeployStatus::Promoted;
            self.runtime.sampler.record_outcome(promoted);

            // Deposit pheromone on the strategy trail when a mutation is promoted.
            if promoted {
                let strategy_key = proposal_strategy_key(proposal);
                self.runtime
                    .mycelium
                    .deposit_pheromone(strategy_key, 0.2, now_ts);

                // Apply in-process parameter adjustment so the entity's signals
                // shift toward telos within this run, not just in the audit trail.
                if let MutationProposal::ParameterAdjust {
                    entity_id,
                    param,
                    delta,
                    ..
                } = proposal
                {
                    self.runtime.apply_live_param(entity_id, param, *delta);
                    let total = self.runtime.get_live_param(entity_id, param);
                    eprintln!("[live_param] {entity_id}:{param} Δ{delta:+.4} (total {total:+.4})");
                    // Saturation detection: same param+direction promoted repeatedly
                    // without structural change → T1 ceiling.
                    let pos = *delta > 0.0;
                    let entry = self
                        .saturation_track
                        .entry(entity_id.clone())
                        .or_insert_with(|| (param.clone(), pos, 0));
                    if entry.0 == *param && entry.1 == pos {
                        entry.2 += 1;
                        if entry.2 == self.config.tier1_fail_threshold * 2 {
                            // T1 ceiling reached — escalate solver tier if not already at T4.
                            let raw = self.runtime.get_live_param(entity_id, "solver_tier");
                            let current = (raw + 1.0) as u8;
                            if current < 4 {
                                self.runtime.apply_live_param(entity_id, "solver_tier", 1.0);
                                eprintln!(
                                    "[tier_up] {entity_id}: T{current} → T{} \
                                     (solver escalated on saturation of {param} ×{})",
                                    current + 1,
                                    entry.2
                                );
                            } else {
                                eprintln!(
                                    "[saturation] {entity_id}:{param} promoted {} times in same direction — \
                                     T4 ceiling reached, meiosis required for structural escape",
                                    entry.2
                                );
                            }
                        }
                    } else {
                        *entry = (param.clone(), pos, 1);
                    }

                    // T4 GP-UCB feedback: record drift improvement for the promoted metric.
                    let prev_score = self
                        .runtime
                        .evaluate_all_drift(self.config.drift_lookback)
                        .ok()
                        .and_then(|evts| {
                            evts.into_iter()
                                .find(|e| e.entity_id == *entity_id)
                                .map(|e| e.score)
                        })
                        .unwrap_or(0.0);
                    let improvement = 0.5 - prev_score; // positive when score < 0.5
                    let history = self.t4_history.entry(entity_id.clone()).or_default();
                    let total_obs = self.t4_total_obs.entry(entity_id.clone()).or_insert(0);
                    solver_tiers::gp_observe(history, total_obs, param, improvement);
                }

                // Each promoted mutation is a division event — ages the entity's
                // telomere. When exhausted, enforce the on_exhaustion policy.
                // Skip already-Dead entities to avoid duplicate apoptosis logs when
                // multiple proposals for the same entity are promoted in one tick.
                let eid = proposal.primary_entity();
                let already_dead = self
                    .runtime
                    .supervisor
                    .get(eid)
                    .map(|e| !e.is_alive())
                    .unwrap_or(false);
                if already_dead {
                    deploy_outcomes.push(outcome);
                    continue;
                }
                if let Err(msg) = self
                    .runtime
                    .supervisor
                    .record_division(eid, &self.runtime.store)
                {
                    eprintln!("[telomere] {msg}");
                    let on_exhaustion = self
                        .runtime
                        .supervisor
                        .get(eid)
                        .and_then(|e| e.on_exhaustion.as_deref())
                        .unwrap_or("senescence");
                    if on_exhaustion == "apoptosis" {
                        self.runtime.supervisor.transition(
                            eid,
                            EntityState::Dead,
                            &self.runtime.store,
                        );
                        eprintln!("[apoptosis] entity '{eid}' killed after telomere exhaustion");
                    }
                }
            }
            deploy_outcomes.push(outcome);
        }

        Ok(TickResult {
            drift_events,
            proposals: accepted,
            tier_used,
            deploy_outcomes,
            circadian_suppressed: suppressed,
            distillation_ran,
            gossip_absorbed,
            security_absorbed,
        })
    }

    /// Run the daemon loop. Blocks the calling thread. Returns on `stop_requested`.
    ///
    /// Use `std::thread::spawn` to run in the background.
    pub fn run_loop(&mut self, stop_requested: &std::sync::atomic::AtomicBool) {
        while !stop_requested.load(std::sync::atomic::Ordering::Relaxed) {
            let _ = self.run_once();
            std::thread::sleep(self.config.tick_interval);
        }
    }

    // ── Tier cascade ─────────────────────────────────────────────────────────

    fn propose_for_event(&mut self, event: &DriftEvent) -> (Vec<MutationProposal>, u8) {
        let eid = event.entity_id.clone();

        // ── Solver tier dispatch ──────────────────────────────────────────────
        // Each entity carries a solver_tier in live_params (0.0 = default → T1).
        // Tiers 2-4 replace the Polycephalum rule engine with their own internal
        // algorithm. The AI cascade (Haiku/Sonnet) still fires as a fallback when
        // the entity's internal solver fails to converge.
        let solver_tier_raw = self.runtime.get_live_param(&eid, "solver_tier");
        // raw=0.0 → T1, raw=1.0 → T2, raw=2.0 → T3, raw=3.0 → T4
        let effective_tier = ((solver_tier_raw + 1.0) as u8).min(4).max(1);

        let internal_proposals: Vec<MutationProposal> = match effective_tier {
            1 => {
                // T1 — Polycephalum deterministic rule engine (existing behavior).
                self.runtime.propose_mutations(event, None)
            }
            2 => {
                // T2 — SA-inspired: Boltzmann exploration, temperature decays each tick.
                let temp = self.t2_temperature.entry(eid.clone()).or_insert(5.0);
                let mut rng = self.rng_state ^ eid.len() as u64;
                let proposals = solver_tiers::t2_sa(event, *temp, &mut rng);
                self.rng_state = rng;
                *temp = (*temp * 0.98).max(0.01); // geometric cooling
                proposals
            }
            3 => {
                // T3 — SARSA hyper-heuristic: weight-table selection over proposal types.
                let weights = self
                    .t3_weights
                    .entry(eid.clone())
                    .or_insert([1.0 / 3.0; N_HEURISTICS]);
                let epsilon = 0.1;
                let mut rng = self.rng_state ^ (eid.len() as u64).wrapping_mul(99991);
                let (proposals, _) = solver_tiers::t3_sarsa(event, weights, epsilon, &mut rng);
                self.rng_state = rng;
                proposals
            }
            _ => {
                // T4 — GP-UCB surrogate: picks the metric with highest upper confidence bound.
                let history = self.t4_history.entry(eid.clone()).or_default();
                let total_obs = self.t4_total_obs.entry(eid.clone()).or_insert(0);
                solver_tiers::t4_gp_ucb(event, history, &[], 1.0, *total_obs)
            }
        };

        if !internal_proposals.is_empty() {
            self.tier1_fail_counts.insert(eid.clone(), 0);
            return (internal_proposals, effective_tier.min(1));
        }

        // Internal solver produced nothing — fall through to AI cascade.
        let t1_fails = self.tier1_fail_counts.entry(eid.clone()).or_insert(0);
        *t1_fails += 1;

        if *t1_fails < self.config.tier1_fail_threshold {
            return (vec![], 1);
        }

        // T2 cooldown — prevent runaway API spend when T1 is always silent.
        let last_t2 = self.last_t2_tick.get(&eid).copied().unwrap_or(0);
        if self.tick_count - last_t2 < self.config.t2_min_interval_ticks {
            return (vec![], 1);
        }

        // Tier 2 — Ganglion (Haiku).
        self.last_t2_tick.insert(eid.clone(), self.tick_count);
        let corpus = crate::runtime::ganglion::serialize_corpus(
            &event.entity_id,
            event,
            &self.runtime.store,
            self.runtime.ganglion.config.corpus_lookback,
        );
        let t2_proposals = self.runtime.ganglion.evaluate_with_corpus(event, &corpus);

        if !t2_proposals.is_empty() {
            self.tier2_fail_counts.insert(eid.clone(), 0);

            // ── BIOISO escalation path ────────────────────────────────────────
            // T2 (Haiku) defaults to parameter_adjust — it rarely proposes
            // structural_rewire even when structurally required.  When drift
            // exceeds the rewire threshold, additionally invoke T3 (Sonnet) so
            // it can recognise whether structural self-modification is needed.
            let has_rewire = t2_proposals
                .iter()
                .any(|p| matches!(p, MutationProposal::StructuralRewire { .. }));
            let high_drift = event.score > self.config.structural_rewire_threshold;

            if has_rewire || high_drift {
                let t3_proposals = self.runtime.evaluate_tier3(event, None);
                if !t3_proposals.is_empty() {
                    return (t3_proposals, 3);
                }
            }

            return (t2_proposals, 2);
        }

        let t2_fails = self.tier2_fail_counts.entry(eid.clone()).or_insert(0);
        *t2_fails += 1;

        if *t2_fails < self.config.tier2_fail_threshold {
            return (vec![], 2);
        }

        // Tier 3 fallback — Mammal Brain (Sonnet) when T2 is consistently silent.
        let t3_proposals = self.runtime.evaluate_tier3(event, None);
        if !t3_proposals.is_empty() {
            self.tier2_fail_counts.insert(eid, 0);
            return (t3_proposals, 3);
        }

        (vec![], 3)
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Derive a pheromone strategy key from a mutation proposal variant.
fn proposal_strategy_key(proposal: &MutationProposal) -> String {
    match proposal {
        MutationProposal::ParameterAdjust { param, .. } => format!("adjust:{param}"),
        MutationProposal::EntityPrune { .. } => "prune".to_string(),
        MutationProposal::EntityRollback { .. } => "rollback".to_string(),
        MutationProposal::EntityClone { .. } => "clone".to_string(),
        MutationProposal::StructuralRewire { signal_name, .. } => {
            format!("rewire:{signal_name}")
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::polycephalum::{DeltaSpec, Rule, RuleAction, RuleCondition, RuleRegistry};

    fn default_orchestrator() -> Orchestrator {
        let rt = Runtime::new(":memory:").unwrap();
        Orchestrator::new(rt, OrchestratorConfig::default())
    }

    #[test]
    fn tick_with_no_entities_returns_empty_result() {
        let mut orch = default_orchestrator();
        let result = orch.run_once().unwrap();
        assert!(result.drift_events.is_empty());
        assert!(result.proposals.is_empty());
        assert!(result.tier_used.is_none());
    }

    #[test]
    fn tick_with_no_drift_returns_empty_result() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("e1", "Test", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("e1", "temperature", Some(0.0), Some(100.0), Some(50.0))
            .unwrap();
        // Emit a signal well within bounds.
        orch.runtime.emit_metric("e1", "temperature", 50.0).unwrap();
        let result = orch.run_once().unwrap();
        assert!(result.drift_events.is_empty());
    }

    #[test]
    fn tick_with_drift_invokes_tier1_when_rule_matches() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("forest", "ForestModel", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("forest", "carbon_stock", Some(0.0), Some(100.0), Some(80.0))
            .unwrap();

        // Register a Tier 1 rule.
        let rule = Rule {
            name: "boost_carbon".into(),
            priority: 10,
            condition: RuleCondition {
                metric: "carbon_stock".into(),
                min_score: 0.3,
                max_score: 1.01,
                min_severity: crate::runtime::DriftSeverity::Healthy,
            },
            action: RuleAction::AdjustParam {
                param: "carbon_input".into(),
                delta: DeltaSpec::Fixed(5.0),
            },
        };
        let mut registry = RuleRegistry::new();
        registry.add_for_entity("forest", rule);
        orch.runtime.polycephalum = crate::runtime::Polycephalum::with_registry(registry);

        // Emit a drifted signal.
        orch.runtime
            .emit_metric("forest", "carbon_stock", 5.0)
            .unwrap();

        let result = orch.run_once().unwrap();
        // Drift should have been detected.
        assert!(!result.drift_events.is_empty());
        // Tier 1 should have fired (even if gate rejects — tier_used reflects the tier that
        // produced proposals, not whether they passed the gate).
        assert_eq!(result.tier_used, Some(1));
    }

    #[test]
    fn tier1_fail_counter_increments_on_miss() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("ent", "E", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("ent", "m", Some(0.0), Some(1.0), Some(0.9))
            .unwrap();
        // Emit a badly drifted value — no Tier 1 rules registered, so T1 will miss.
        orch.runtime.emit_metric("ent", "m", 0.0).unwrap();
        let _ = orch.run_once();
        let count = *orch.tier1_fail_counts.get("ent").unwrap_or(&0);
        assert_eq!(count, 1);
    }

    #[test]
    fn mycelium_tick_called_each_run_once() {
        // Mycelium tick increments; we verify that after N run_once calls the
        // metabolic EMA has been updated (non-zero ticks seen).
        let mut orch = default_orchestrator();
        for _ in 0..5 {
            orch.run_once().unwrap();
        }
        // After 5 ticks with 0 signals, metabolic load should be 0 (EMA of 0),
        // but the tick count on the orchestrator must be 5.
        assert_eq!(orch.tick_count, 5);
    }

    #[test]
    fn distillation_runs_on_configured_interval() {
        let mut cfg = OrchestratorConfig::default();
        cfg.epigenome_distil_interval = 3;
        let rt = Runtime::new(":memory:").unwrap();
        let mut orch = Orchestrator::new(rt, cfg);

        let r1 = orch.run_once().unwrap(); // tick 1
        let r2 = orch.run_once().unwrap(); // tick 2
        let r3 = orch.run_once().unwrap(); // tick 3 — distil fires
        assert!(!r1.distillation_ran);
        assert!(!r2.distillation_ran);
        assert!(r3.distillation_ran);
    }

    #[test]
    fn circadian_suppress_reduces_active_events() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("gated", "Gated", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("gated", "x", Some(0.0), Some(1.0), Some(0.9))
            .unwrap();

        // Add a Suppress schedule matching every minute (wildcard = always matches).
        orch.runtime
            .circadian
            .add_gate(
                "always_suppress",
                "* * * * *",
                crate::runtime::CircadianAction::Suppress,
                Some("gated".into()),
            )
            .expect("invalid cron expression");

        // Emit a drifted signal.
        orch.runtime.emit_metric("gated", "x", 0.0).unwrap();

        let result = orch.run_once().unwrap();
        // Drift is detected, but the circadian gate suppresses mutations.
        assert_eq!(
            result.circadian_suppressed, 1,
            "expected 1 suppressed event"
        );
        assert!(result.proposals.is_empty(), "no proposals when suppressed");
    }

    #[test]
    fn sampler_acceptance_updated_after_promoted_deploy() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("e1", "E1", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("e1", "v", Some(0.0), Some(100.0), Some(50.0))
            .unwrap();

        // Register a rule so Tier 1 proposes something.
        let rule = Rule {
            name: "boost_v".into(),
            priority: 10,
            condition: RuleCondition {
                metric: "v".into(),
                min_score: 0.3,
                max_score: 1.01,
                min_severity: crate::runtime::DriftSeverity::Healthy,
            },
            action: RuleAction::AdjustParam {
                param: "v_input".into(),
                delta: DeltaSpec::Fixed(5.0),
            },
        };
        let mut registry = RuleRegistry::new();
        registry.add_for_entity("e1", rule);
        orch.runtime.polycephalum = crate::runtime::Polycephalum::with_registry(registry);

        // Emit a badly-drifted signal — gate will reject the proposal but
        // that counts as negative feedback to the sampler.
        orch.runtime.emit_metric("e1", "v", 2.0).unwrap();
        orch.run_once().unwrap();

        // Sampler should have recorded at least one outcome.
        assert!(!orch.runtime.sampler.acceptance.is_empty());
    }

    #[test]
    fn gossip_inbound_absorbed_into_epigenome_as_relational_memory() {
        let mut orch = default_orchestrator();
        // Inject a gossip message directly into mycelium's inbound queue.
        let msg = crate::runtime::GossipMessage {
            sender_id: "remote_peer".into(),
            core_snapshot: r#"{"key":"learned_pattern","value":42}"#.into(),
            ts: 1_000,
        };
        orch.runtime.mycelium.receive_gossip(msg, 1_000);

        let result = orch.run_once().unwrap();
        assert_eq!(
            result.gossip_absorbed, 1,
            "expected 1 gossip message absorbed"
        );
        // Epigenome should now have a Relational Core entry from the peer.
        let entries = orch.runtime.epigenome.core_entries("remote_peer");
        assert!(
            !entries.is_empty(),
            "expected relational memory from gossip"
        );
        assert!(
            entries[0].content.contains("gossip@"),
            "content should have gossip tag"
        );
    }

    #[test]
    fn pheromone_deposited_on_promoted_mutation() {
        let mut orch = default_orchestrator();
        orch.runtime
            .spawn_entity("e2", "E2", "{}", None, None)
            .unwrap();
        orch.runtime
            .set_telos_bounds("e2", "load", Some(0.0), Some(100.0), Some(20.0))
            .unwrap();
        let rule = Rule {
            name: "reduce_load".into(),
            priority: 10,
            condition: RuleCondition {
                metric: "load".into(),
                min_score: 0.3,
                max_score: 1.01,
                min_severity: crate::runtime::DriftSeverity::Healthy,
            },
            action: RuleAction::AdjustParam {
                param: "load_shedding".into(),
                delta: DeltaSpec::Fixed(5.0),
            },
        };
        let mut registry = RuleRegistry::new();
        registry.add_for_entity("e2", rule);
        orch.runtime.polycephalum = crate::runtime::Polycephalum::with_registry(registry);

        // Emit a signal inside bounds — drift but valid loom code accepted.
        orch.runtime.emit_metric("e2", "load", 80.0).unwrap();
        orch.run_once().unwrap();

        // Pheromone trail for "adjust:load_shedding" may exist if promotion succeeded.
        // We assert the method doesn't panic and returns a value in [0, 1].
        let strength = orch
            .runtime
            .mycelium
            .pheromone_strength("adjust:load_shedding");
        assert!(strength >= 0.0 && strength <= 1.0);
    }
}
