//! Semantic analysis for the Loom compiler.
//!
//! Re-exports the two checker passes so callers can write:
//!
//! ```rust,ignore
//! use loom::checker::{TypeChecker, EffectChecker};
//! ```

pub mod algebraic;
pub mod aspect;
pub mod boundary;
pub mod canalization;
pub mod category;
pub mod checkpoint;
pub mod cognitive_memory;
pub mod conservation;
pub mod criticality;
pub mod curryhow;
pub mod degeneracy;
pub mod dependent;
pub mod effect_handler;
pub mod effects;
pub mod errorcorrection;
pub mod evolution_vector;
pub mod exhaustiveness;
pub mod gradual;
pub mod hgt;
pub mod infer;
pub mod infoflow;
pub mod journal;
pub mod loom_checker;
pub mod manifest;
pub mod messaging;
pub mod migration;
pub mod minimal;
pub mod nichect;
pub mod pathway;
pub mod privacy;
pub mod probabilistic;
pub mod property_checker;
pub mod provenance;
pub mod randomness;
pub mod refinement;
pub mod resonance;
pub mod safety;
pub mod scenario;
pub mod selfcert;
pub mod semiosis;
pub mod senescence;
pub mod separation;
pub mod session;
pub mod sidechannel;
pub mod signal_attention;
pub mod smt_bridge;
pub mod stochastic;
pub mod store;
pub mod symbiosis;
pub mod teleos;
pub mod temporal;
pub mod tensor;
pub mod types;
pub mod typestate;
pub mod umwelt;
pub mod units;
pub mod usecase;
pub mod entity;

pub use algebraic::AlgebraicChecker;
pub use aspect::AspectChecker;
pub use boundary::BoundaryChecker;
pub use canalization::CanalizationChecker;
pub use category::CategoryChecker;
pub use checkpoint::CheckpointChecker;
pub use cognitive_memory::CognitiveMemoryChecker;
pub use conservation::ConservationChecker;
pub use criticality::CriticalityChecker;
pub use curryhow::CurryHowardChecker;
pub use degeneracy::DegeneracyChecker;
pub use dependent::DependentChecker;
pub use effect_handler::EffectHandlerChecker;
pub use effects::EffectChecker;
pub use errorcorrection::ErrorCorrectionChecker;
pub use evolution_vector::EvolutionVectorChecker;
pub use exhaustiveness::ExhaustivenessChecker;
pub use gradual::GradualChecker;
pub use hgt::HgtChecker;
pub use infer::InferenceEngine;
pub use infoflow::InfoFlowChecker;
pub use journal::JournalChecker;
pub use loom_checker::{
    CheckerStage, LoomChecker, RandomnessCheckerAdapter, SafetyCheckerAdapter,
    StochasticCheckerAdapter, TeleosCheckerAdapter,
};
pub use manifest::ManifestChecker;
pub use messaging::MessagingChecker;
pub use migration::MigrationChecker;
pub use minimal::MinimalChecker;
pub use nichect::NicheConstructionChecker;
pub use pathway::PathwayChecker;
pub use privacy::PrivacyChecker;
pub use probabilistic::ProbabilisticChecker;
pub use property_checker::PropertyChecker;
pub use provenance::ProvenanceChecker;
pub use randomness::RandomnessChecker;
pub use refinement::RefinementChecker;
pub use resonance::ResonanceChecker;
pub use safety::SafetyChecker;
pub use scenario::ScenarioChecker;
pub use selfcert::SelfCertChecker;
pub use semiosis::SemiosisChecker;
pub use senescence::SenescenceChecker;
pub use separation::SeparationChecker;
pub use session::SessionChecker;
pub use sidechannel::SideChannelChecker;
pub use signal_attention::SignalAttentionChecker;
pub use smt_bridge::SmtBridgeChecker;
pub use stochastic::StochasticChecker;
pub use store::StoreChecker;
pub use symbiosis::SymbiosisChecker;
pub use teleos::check as check_teleos;
pub use temporal::TemporalChecker;
pub use tensor::TensorChecker;
pub use types::TypeChecker;
pub use typestate::TypestateChecker;
pub use umwelt::UmweltChecker;
pub use units::UnitsChecker;
pub use usecase::UseCaseChecker;
pub use entity::EntityChecker;
