//! Mesa (Python ABM) simulation emitter.
//!
//! Converts Loom biological beings and ecosystems into a runnable
//! Python Mesa agent-based simulation. Each being becomes an Agent,
//! each ecosystem becomes a Model with a scheduler.
//!
//! Mesa: https://mesa.readthedocs.io/
//! ABM is the standard tool for simulating complex adaptive systems in
//! biology, economics, and social science.

use crate::ast::{BeingDef, EcosystemDef, Module};

/// Emits a Mesa (Python ABM) simulation from a Loom [`Module`].
pub struct SimulationEmitter;

impl SimulationEmitter {
    pub fn new() -> Self {
        SimulationEmitter
    }

    /// Emit a complete Mesa Python simulation from a [`Module`].
    pub fn emit(&self, module: &Module) -> String {
        let mut out = String::new();
        out.push_str("# Generated by Loom — Mesa Agent-Based Simulation\n");
        out.push_str("# https://mesa.readthedocs.io/\n");
        out.push_str("from mesa import Agent, Model\n");
        out.push_str("from mesa.time import RandomActivation\n");
        out.push_str("from mesa.space import MultiGrid\n\n");

        for being in &module.being_defs {
            out.push_str(&self.emit_agent(being));
            out.push('\n');
        }

        for ecosystem in &module.ecosystem_defs {
            out.push_str(&self.emit_model(ecosystem, module));
            out.push('\n');
        }

        out
    }

    fn emit_agent(&self, being: &BeingDef) -> String {
        let mut out = String::new();
        let telos_desc = being
            .telos
            .as_ref()
            .map(|t| t.description.as_str())
            .unwrap_or("");
        let describe = being.describe.as_deref().unwrap_or(&being.name);

        out.push_str(&format!("class {}(Agent):\n", being.name));
        out.push_str("    \"\"\"\n");
        out.push_str(&format!("    {}\n", describe));
        out.push_str(&format!("    telos: {}\n", telos_desc));
        out.push_str("    Loom being — Mesa Agent\n");
        out.push_str("    \"\"\"\n\n");

        out.push_str("    def __init__(self, unique_id, model):\n");
        out.push_str("        super().__init__(unique_id, model)\n");
        if let Some(matter) = &being.matter {
            for field in &matter.fields {
                out.push_str(&format!(
                    "        self.{} = None  # {}\n",
                    field.name,
                    format!("{:?}", field.ty)
                        .replace("Base(", "")
                        .replace(")", "")
                ));
            }
        }
        out.push_str("        self._fitness = 0.0\n");
        out.push_str("        self._distance_to_telos = float('inf')\n\n");

        // step method
        let evolve_constraint = being
            .evolve_block
            .as_ref()
            .map(|e| e.constraint.as_str())
            .unwrap_or("");
        out.push_str("    def step(self):\n");
        out.push_str("        \"\"\"Teleological loop: directed search toward telos.\n");
        out.push_str("        E[distance_to_telos] must be non-increasing.\n");
        if !evolve_constraint.is_empty() {
            out.push_str(&format!("        {}\n", evolve_constraint));
        }
        out.push_str("        \"\"\"\n");
        out.push_str("        self._regulate()\n");
        out.push_str("        self._evolve_step()\n");
        out.push_str("        self._fitness = self._compute_fitness()\n\n");

        // _regulate method
        out.push_str("    def _regulate(self):\n");
        out.push_str("        \"\"\"Homeostatic regulation.\n");
        for reg in &being.regulate_blocks {
            let (low, high) = reg
                .bounds
                .as_ref()
                .map(|(l, h)| (l.as_str(), h.as_str()))
                .unwrap_or(("?", "?"));
            out.push_str(&format!(
                "        {} → target {} within [{}, {}]\n",
                reg.variable, reg.target, low, high
            ));
        }
        out.push_str("        \"\"\"\n");
        out.push_str("        pass  # todo: implement homeostasis\n\n");

        // _evolve_step method
        out.push_str("    def _evolve_step(self):\n");
        out.push_str(&format!(
            "        \"\"\"Directed evolution toward telos: {}\"\"\"\n",
            telos_desc
        ));
        out.push_str("        pass  # todo: implement evolution step\n\n");

        // _compute_fitness method
        out.push_str("    def _compute_fitness(self) -> float:\n");
        out.push_str(&format!("        \"\"\"telos: {}\"\"\"\n", telos_desc));
        out.push_str("        return 0.0  # todo: implement fitness\n");

        out
    }

    fn emit_model(&self, ecosystem: &EcosystemDef, _module: &Module) -> String {
        let mut out = String::new();
        let telos = ecosystem.telos.as_deref().unwrap_or("");
        let describe = ecosystem.describe.as_deref().unwrap_or(&ecosystem.name);
        let members_str = ecosystem.members.join(", ");

        out.push_str(&format!("class {}(Model):\n", ecosystem.name));
        out.push_str("    \"\"\"\n");
        out.push_str(&format!("    {}\n", describe));
        out.push_str(&format!("    telos: {}\n", telos));
        out.push_str("    Loom ecosystem — Mesa Model\n");
        out.push_str(&format!("    members: {}\n", members_str));
        out.push_str("    \"\"\"\n\n");

        out.push_str("    def __init__(self, n_agents=10):\n");
        out.push_str("        self.schedule = RandomActivation(self)\n");
        out.push_str("        self.running = True\n");
        out.push_str("        # initialize member beings\n");
        for member in &ecosystem.members {
            out.push_str(&format!(
                "        for i in range(n_agents): self.schedule.add({}(i, self))\n",
                member
            ));
        }
        out.push('\n');

        // step method
        out.push_str("    def step(self):\n");
        out.push_str(
            "        \"\"\"Run one timestep: all agents step, then check quorum signals.\"\"\"\n",
        );
        out.push_str("        self.schedule.step()\n");
        for sig in &ecosystem.signals {
            let snake = to_snake_case(&sig.name);
            out.push_str(&format!("        self._check_quorum_{}()\n", snake));
        }
        out.push('\n');

        // quorum methods for each signal
        for sig in &ecosystem.signals {
            let snake = to_snake_case(&sig.name);
            out.push_str(&format!("    def _check_quorum_{}(self):\n", snake));
            out.push_str(&format!(
                "        \"\"\"Quorum sensing: {} {} → {}\"\"\"\n",
                sig.name, sig.from, sig.to
            ));
            out.push_str("        # count agents signaling\n");
            out.push_str("        pass  # todo: implement quorum detection\n\n");
        }

        out
    }
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    out
}
