#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# setup-hooks.sh — Install git pre-commit hooks from .claude/hooks/
#
# Run once after cloning:  bash scripts/setup-hooks.sh
#
# Hooks installed into .git/hooks/pre-commit:
#   1. pre-commit-secrets        — block accidental credential exposure
#   2. pre-commit-prod-quality   — anti-pattern scan (.unwrap(), todo!, unsafe)
#   3. pre-commit-branch-check   — no direct commits to main/master
#   4. pre-commit-format         — cargo fmt on staged .rs files
#   5. pre-commit-compile        — cargo check on staged .rs files
#   6. pre-commit-clippy         — cargo clippy --all-targets --all-features
#   7. pre-commit-tdd-check      — TDD RED gate: test-only commits must fail
#   8. pre-commit-test           — cargo test (skips docs/config-only commits)
#   9. pre-commit-coverage       — cargo tarpaulin if available, else cargo test
# ──────────────────────────────────────────────────────────────────────

set -e

HOOKS_SRC=".claude/hooks"
GIT_HOOKS=".git/hooks"

if [ ! -d ".git" ]; then
  echo "⚠️  Not a git repository root — skipping hook installation."
  exit 0
fi

if [ ! -d "$HOOKS_SRC" ]; then
  echo "⚠️  $HOOKS_SRC not found — skipping hook installation."
  exit 0
fi

mkdir -p "$GIT_HOOKS"

# ── Build composite pre-commit hook ──────────────────────────────────
PRE_COMMIT="$GIT_HOOKS/pre-commit"

cat > "$PRE_COMMIT" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
# Re-run `bash scripts/setup-hooks.sh` to regenerate.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"

run_hook() {
  local hook="$1"
  local path="$HOOKS_DIR/$hook"
  if [ -f "$path" ]; then
    bash "$path"
    local exit_code=$?
    if [ $exit_code -ne 0 ]; then
      echo "❌ Hook failed: $hook (exit $exit_code)"
      exit $exit_code
    fi
  fi
}

run_hook "pre-commit-secrets.sh"
run_hook "pre-commit-prod-quality.sh"
run_hook "pre-commit-branch-check.sh"
run_hook "pre-commit-format.sh"
run_hook "pre-commit-compile.sh"
run_hook "pre-commit-clippy.sh"
run_hook "pre-commit-tdd-check.sh"
run_hook "pre-commit-test.sh"
run_hook "pre-commit-coverage.sh"

exit 0
EOF

chmod +x "$PRE_COMMIT"

# ── Install commit-msg hook (conventional commit enforcement) ─────────
COMMIT_MSG_HOOK="$GIT_HOOKS/commit-msg"

cat > "$COMMIT_MSG_HOOK" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
HOOKS_DIR="$(git rev-parse --show-toplevel)/.claude/hooks"
HOOK="$HOOKS_DIR/commit-msg.sh"
if [ -f "$HOOK" ]; then
  bash "$HOOK" "$1"
  exit $?
fi
exit 0
EOF

chmod +x "$COMMIT_MSG_HOOK"

# ── Install pre-push hook ─────────────────────────────────────────────
PRE_PUSH="$GIT_HOOKS/pre-push"

cat > "$PRE_PUSH" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  while read local_ref local_sha remote_ref remote_sha; do
    if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
      echo "❌ Deleting remote $BRANCH branch is blocked."
      exit 1
    fi
  done
fi
exit 0
EOF

chmod +x "$PRE_PUSH"

echo "✅ Git hooks installed:"
echo "   .git/hooks/pre-commit — secrets, quality, branch, format, cargo check, clippy, TDD, tests, coverage"
echo "   .git/hooks/commit-msg — conventional commit format"
echo "   .git/hooks/pre-push   — blocks branch deletion on main/master"
echo ""
echo "   Source hooks in:      .claude/hooks/"
echo "   To skip (emergency):  git commit --no-verify"
