//! Multi-module project compilation for the Loom compiler.
//!
//! # Usage
//!
//! ```rust,ignore
//! let manifest = ProjectManifest::from_str(&toml_src)?;
//! build_project(&manifest.module_paths(), &manifest.output)?;
//! ```

use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::LoomError;

// ── Manifest ──────────────────────────────────────────────────────────────────

/// Raw TOML structure for the `[project]` section.
#[derive(Deserialize)]
struct RawManifest {
    project: RawProject,
}

#[derive(Deserialize)]
struct RawProject {
    name: Option<String>,
    #[allow(dead_code)]
    version: Option<String>,
    #[serde(default)]
    modules: Vec<String>,
    #[serde(default = "default_output")]
    output: String,
}

fn default_output() -> String {
    "out/".to_string()
}

/// Parsed `loom.toml` project manifest.
#[derive(Debug, Clone)]
pub struct ProjectManifest {
    pub name: String,
    pub modules: Vec<String>,
    pub output: String,
}

impl ProjectManifest {
    /// Parse a `loom.toml` string into a [`ProjectManifest`].
    ///
    /// Returns `Err` if the TOML is malformed or the `name` field is absent.
    pub fn from_str(toml_src: &str) -> Result<Self, String> {
        let raw: RawManifest =
            toml::from_str(toml_src).map_err(|e| format!("manifest parse error: {}", e))?;
        let name = raw
            .project
            .name
            .ok_or_else(|| "manifest missing required field: name".to_string())?;
        Ok(ProjectManifest {
            name,
            modules: raw.project.modules,
            output: raw.project.output,
        })
    }
}

// ── Build orchestrator ────────────────────────────────────────────────────────

/// Compile a list of `.loom` files and write the generated `.rs` files plus a
/// `lib.rs` to `output_dir`.
///
/// Each input path is compiled independently with `loom::compile`.  All errors
/// are aggregated; on the first file that fails the whole build stops and
/// returns `Err`.
pub fn build_project(
    module_paths: &[&str],
    output_dir: &str,
) -> Result<(), Vec<LoomError>> {
    let out_path = Path::new(output_dir);
    std::fs::create_dir_all(out_path).map_err(|e| {
        vec![LoomError::CodegenError {
            msg: format!("cannot create output dir `{}`: {}", output_dir, e),
            span: crate::ast::Span::synthetic(),
        }]
    })?;

    let mut mod_names: Vec<String> = Vec::new();

    for &loom_file in module_paths {
        let source = std::fs::read_to_string(loom_file).map_err(|e| {
            vec![LoomError::CodegenError {
                msg: format!("cannot read `{}`: {}", loom_file, e),
                span: crate::ast::Span::synthetic(),
            }]
        })?;

        let rust_src = crate::compile(&source)?;

        // Derive the output filename from the input stem (e.g. `alpha.loom` → `alpha.rs`).
        let stem = PathBuf::from(loom_file)
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "module".to_string());

        let out_file = out_path.join(format!("{}.rs", stem));
        std::fs::write(&out_file, &rust_src).map_err(|e| {
            vec![LoomError::CodegenError {
                msg: format!("cannot write `{}`: {}", out_file.display(), e),
                span: crate::ast::Span::synthetic(),
            }]
        })?;

        mod_names.push(stem);
    }

    // Emit `lib.rs` that re-exports every compiled module.
    let lib_rs = emit_lib_rs(&mod_names);
    let lib_path = out_path.join("lib.rs");
    std::fs::write(&lib_path, lib_rs).map_err(|e| {
        vec![LoomError::CodegenError {
            msg: format!("cannot write lib.rs: {}", e),
            span: crate::ast::Span::synthetic(),
        }]
    })?;

    Ok(())
}

// ── lib.rs emitter ────────────────────────────────────────────────────────────

fn emit_lib_rs(module_stems: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by `loom build`. Do not edit manually.\n\n");
    for stem in module_stems {
        out.push_str(&format!("#[path = \"{}.rs\"]\n", stem));
        out.push_str(&format!("pub mod {};\n", stem));
    }
    out
}
